apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  app: {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - name:  {{ .Values.appName }}
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}