apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.appName }}-ingress
  app: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/priority: "2"
spec:
  rules:
    - host: {{ .Values.ingress.hosts.host }}
      http:
        paths:
          - path: {{ .Values.ingress.hosts.paths }}
            backend:
              serviceName: {{ .Values.appName }}
              servicePort: {{ .Values.appName }}